---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: vocabolario
spec:
  encryptedData:
    password: AgCu092Op7HT694jeAqYu5k+jMt23nL/hFtazYanbfKNKX6Cl81weTKE8A69FjuU9YEnSRAvGc1Tk9SvKSWqAwBUQOq4SnBIIK85eNF/SJnEL4bG7QGA0nv3hGSXAZau6Pq/7NgV7HblfMO7Sf00QZ3Z9z2VK486yB/w+ZKmJTZxOYqm+4AqSqb8Mc1wzTwrKfHO0sTtoPqAOfoAxXVnhkDh50TbCkiRfedajNB9sujIiqH5p/H2DRBK8El033oPzkE5pvWwjo7Ab2fgY+TjGQemcL6fDN8hSFQ5Xi1lFqrHpRKyopiWTJToj9gdGCrOkt5xQPSuLrF5wJJu+BM4MC5pSER8tTEPkeWMlIhlZfTZPNbgEBiy0e49vF4olXRQhO5HCdpKu+aGIngTDIJDQWscQ8Jm5ufukUZXl+XZIpwLLhCFJEeNyLblAloAlB9P05x3EhaaL3aaSzsmx5l/cF/ua5k+CJihQp+5W1bGrLijOkjKxdNYbzlAKJz5oUFIO55jw8kbbKYcn8sQC2FOb5flcajsaB8NJOsc7Oo9nA/agOKaJB0R3fqbt0ipvzuQnUNBA2+g80xOCtQiLPIxtjWNYtqCKlq6yZ2ziFRqNKoBdCJlY1yylyH0zyP6DOhifSD8vDEqUyv+DWB2BaxIxh/RNRWWp7/1d9yaiCBg4iepVZghs+QHyVNunuWZWyCsDM7xWXO0grRltG6tPRa3EhUyp8LRuA==
    username: AgCTSvSEu/ohqjt/mgDO+7lrmcMV+Ix4f/tVP4LkH3SMFmi4dCi6v/E4gn4r6vCyZ3B8RIl5GOEqHrJ/0O9z4TZ8kDSvRzwxZV6m0nyxOKCHOL7b9oVt/o254C9of6WiyMOA7nY09GICrzHEQxYZP8gduwz8G8O5ggBpCD0QujtBcVKLKZcQH0NTDA82Z+j8wgDJve6Qx5Sbuj+TmPWMRviyWjDyKYiReNapWWjkQKySJXkPk9o9pp26GeD8nODg5MW2BhSt7Wg1MR7D2NdmlcDM26GN1MZOSUFaVPpjmb5P9PlZ58iqMVWLqlGN4z7mkpopueFfoT+OVRBVbjpm9SB5iH+acYzosEkjvGBsJo8+kuKqtBnQVwmBDKqWSYvJbxG9wvONOi5T6smaNtYbMtBZC8HMNaxt/aGuK/IwIkrPO9JT643q0CXlH9xmp0xUCSBfz+jx7V3bIVbiQ9s74TClBaULWLpQll/MKl0yDuOe+9XhxRpnRRvRFpzHsmxvabL8mWJhJmPPY6Jdk0BhxUBV5b+GOOR9NwkeJPYJRsWJFwwzMImXrLLbsJjr7TlTCL+UnPtDsMJ4hN9Ttz9VZr6NtXhwCI0TOOWKNDyuzb6eYTCVlZIevpJOvG6nWRLY8pexKjmq/J6nVxnnTjojpiU8+vW7VVlf0l9T1lymzfEXmAmAIyE7G8NHkib06ut8guhd5LT6Ul40NXO1aA==
  template:
    metadata:
      name: db-secret
      namespace: vocabolario
    type: Opaque
