---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vocabolario-app
  namespace: vocabolario
spec:
  encryptedData:
    password: AgCtv+te9bAdwunDrAQ4eo19nRP/zq126ZUdEyZjnaOZ+AmqTT29du7sm3tGyykGhAdgljSGe+myX1fwmdySg/ROZubNakX98W5OAj6MfhQuXsQJhgxE93t11nSKbpoRYWfxhSEisKpZvf6UiC25gMVHPSh9ku5JMDJDeXO3Uidr+WAmFPFIysyRsah89s3/Ba6jyQUf0KUZ2yfQGOeT0LbOxJPh1LDbyZrCiL7CpwEQGUYjLw/QcXoxsrStCA01WflKJlehFBY5xPVT9CNmG59eO22yVitDf6bAmiutVVXXt/aAhlOQGEsmWsjnGkXWQmcPN+LgRBHHVakTxyzg1qxZEnwW/jZbQhg0Fkl9Zk8QPi/s+Gw1nJzNZx7d+KUnzt6HuNPCtRHlr+Dp9DTkE9q9SabpnQPswLSvCM8W9gHKbvT4wGr3nqPpZFyNHIVD5qKbXDzFTXBvpkEaXCKsUJB5eCPoApAfW8pvcvHMGFQKUvmNvmgYqcm+YotE2AYBY5tOI7oI4ha/EtxJEz8g2O4PvDB/egRRJ1GQe7KevAVeJjD+up1KXa50QZkIv2Qxnuocx4L1JduuYgYlgP+H3eTliwmGaZbCYl/XIn+sIJ1rdloml+NbgzRFC3ByPpfOoDwmn8A9anFjWXktVGme/Zh9gXwB4ngTkd2dK/H6JFLPmbQhiSxjX+HGnJyJImfCtAeVsuQgij9Px1th3JcS8wfd4nNMAQ==
    username: AgA8e1Hn778UaoqGJ2ac2OpqEzBPU5kMArsrS86SNuNrEcz1/5UWaYqp2Wt52wXqIxXaJo64T9eQdGI+5cJh9zK2vC/Yr+iGIYj+/RzkRl4l5NyMJTEn6oG2oPPIwXj3izAzfmNoLb8XjS9NoOIQdqLfMnJalfEgFFKfaoANAfDre4QfrXEctnzFKHB/H63QPJ/whhwU0nFXGOJ7HxWUzIV7d+4khRUDf0XDNDS18/hFDw+bLXj+2+2DArATED3leffjjsWxoZ/wllWxDUxN082gNvrgVDmiykDgl8KF/Y2vgJh/8ZaIhGebEGileyU8pY86go2xUr7bgndmcaz/W8/FOtanq9Z/80+BhyabGuPZhQDMC2/slmDTkB6Qa71JA0gqo3pA91FKt89x47rYsnVxn7+w+oCZ0wijtB5HEirLCc5I7SZyxcSUky4ZWon5cwk6UE9T9PQjMDH4S31/W9CWsSJ+NS4q/2/JoQFQsMYmf38JlrcW0ztyD7LYNJ8YwFzrYMeCQVcpnRzBVkENPSSJN2dP+xmivYe5o3hTR1opBW6Kcl/Aa07Fvz3ptpTXKta+ULOPUqFFyDrxxeu37WGMpPB0nao0INcD+OBjfUg4pibZzL+x7rD0gdXUE7PkWliapuQroOQ3q7YOCfemKImOY2utMEm9Df8S7S7eXzcSA+nrhzWt1W/IVY2XlDdofkgDkh+OAUJfHbFMCg==
  template:
    metadata:
      name: vocabolario-app
      namespace: vocabolario
    type: Opaque
