---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firecrawl-secret
  namespace: vocabolario
spec:
  encryptedData:
    api-key: AgBm7dJmp6VLkNiYVHelkB1v6qvH/HI9fB8SbQP1rj+oDIlIP25lczKbbRIh0l0GByit5Utku8zjN5xu6qH4aYm36/aA7foNdR0PC48Y8Jadp4Zpd1SK+XjcDPiqYTE0vDmEN8qoIrLFFa4WshaWmRSvpbkNPjxl9iGCRyM028+W+QwzbyAbq+ACo0gCfER9vtAsOR77lM3/B1HEzZCQXIHXjUJmqcedOwOaAbr7BONaI7onfxwvkFf+0zP84/6U9c3rujEjtVt7gkhVYMLow3qWRx09OdFPzV0dbJByvrLqUMFAe9AzVnoireYtNoj9Nfp4GOimL37Fv8JF9mzOFpCS2tjLtrsBgw4Zf8FmXFq0EvHCs8RlJXdI+kzLOUe3cnSpBK2pByWmTNmJRcCheeIXZRNcZoWbT0WkXaqh5gUOQW96TMvIf5SqJby/59WEOKi5a9ymbHoDKRXCh7ub0oW3LVFXbpjQg+AZe3Q41K/eRL6C0ONPTPj+VWtHLdkamWadhYBsprXAMIIWqazRp+AfbSmeUmOyxmsHbhZvC2lLyu08EkWiPitfORsR759KHvlI4Q4L9U7bkv35gxPUYfVU4VWKydqJfqQC569Gc9PNWJAcwiPZdActOXXqG6fj3xtfiLynwiyNoHwmi+6nCPoq+keWnJWMu4qW2ARPbSFXbRFPMCurKka//Pd6zn4TnWwKvHrAKOybrELyuagVc5Il2IO4tgJWeE2JiiXCuMAGCpWK5Q==
  template:
    metadata:
      name: firecrawl-secret
      namespace: vocabolario
    type: Opaque
