---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: vocabolario
spec:
  encryptedData:
    jwt-secret-key: AgDFKNQGHpE9aiNu4nQJhKZNq2qiVE2OFNLifjzQD70GkGhpyOqw+ymwjZ/kQDXQ5ydXgkrU/nv70p/E+Kf+gR3tGBtHdHMmX12BK4+aR60sLFj1DDIkSZpXiPdo06jDqc8byEk/t8hYUbcTTSsJnXETyNPY/+7Kc8eJf15vVr7zwVIpwHvm73owEzFfZ+dNMkBWU++TtdeE44h2uxiBLBg3AtxoiN+dOaXXzHTaeIlernNGkxSoOaYEeaBPm9KWbevmuL2qeUyxP1p8QM3Jur2pyDUkMfH00YvmtpjlBzJ3BCWyFWjn2C3/UspweFD6x5m1uwT9TW8y0lVi+dE9KCkItwEnx9i34B1+9WDZaQG9/ksHu/qV6AXsYqxOOAG6alhoUSqrdRT0FNsnTlRbjZMmgsQPWm2D7H3XpC+xi5vJm8VNfXgOevUq/Iho317V24HS7hMPn1xiUoEwz8rsLxIIZt1yuaFtMQkY34E6sTfLo6Xq5Ou8d7ST8pmn+zTkwM4OfHLJjXhrUld/rEBVUD4UE2KqLnLa2c20a2pkAoYRhOItCHi35w561rOPmaIEjHYtbYykmg9ce45mh4OEkNV8vT8q3H4Akf7rR8NTrIWi5XN15rn/itowBPdMuxSk9MFPRfyoKqg3P7dJPYtCE2gDTJU6Yi8iML2TErNCpXq6LNCpwfHDhPqRaLYp9So/xdR+6jNkqWuHcyygEtzwJhnuZ7tG9X6sHuV23gV68luMI8KzhPPxvU0JeP4I+A==
  template:
    metadata:
      name: jwt-secret
      namespace: vocabolario
    type: Opaque