apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: system-backup-daily
  namespace: longhorn-system
spec:
  cron: "0 4 * * *"
  task: system-backup
  retain: 7
  concurrency: 1
  parameters:
    volume-backup-policy: disabled
