apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"    
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  # snap = in-cluster CSI snapshot for Velero data mover
  # bak = Longhorn backup to external backup target (not used here)
  type: snap