---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgC4b5JF1Nb6j13P0+0YIy9LVbKpYQT19RshbUx+bdSWZU9xT8HmzQ7G2K28sVZquZ1yq5gBHUTHsJBWUcsj2vvotcBqM70fgYyD4IBkN4tHH6USwvf4anAb3AQejGML4x9/dJU1GBCNPCoe/fevBElR9jH55SJK2wfAVDEfxUXCJ2yKVTMz+ezkAg//RUNese34QMSKJqk9MUfQzTIYSU/8QUtaJOuor5Ew7pNuNXEif9xXwCd3OOLdV0mw4K74YyQtXEJzpm/x4PEwYXlQ7hEJ3pa5wRAAFH1+W8GctcpG+2SdYtNsaJtccyictLNPV/FbMGyefNqbyTgUutr8T6ahFt1u55AHyMiXivooCHY4w0DCshwdiQDRsdgBDqflDLpnd/YZv/32Ya+rL0HGUfhCFy+73ejVq6RLJperzCp/FFpFUgaJS2qZXV3+9hqb0QPaeuGYtmSEO/0r9j5fgeyOiITtYZ1R+yYWA7DA5sEv4sNrMtv4aMzr8E2Z6S/+h2TzlwDlAojUhpGCFu3DL4gXX/vjE2HkhsLnXpcIBnKkAZ2DRwp7ddw8V4ZntX+LRUX4KXgD5AQhWRq9ZCU/oKprkgv0JBKOUAvr00Ty7gDKX4TqAcfLn4qGB7yCTfgr7XPkQ7woZT9aD1fOc7kp2rslT5u4xlO17SnA7+iRVsKADbrVRJttaaLkHYAoT3iSAJDfCh5PVw==
    secret_key: AgA7bLcLikh/Ebeev1MskIpeu6gv6zEDP238311V1tGMf6tvNsAA2kkdwnMcMFe1Szbd+GkoXla4zywK9c/SAsy6Fh+pfIxhOfxcRw3fufzTv50dh02VZ9N7Ofbqu5smrBeZkkNWyGtpVCEElBXigYF2w8T/r94N//a//y0mxjh8GRWoFKEycY0mTIX843PUDwRmJ+UZ+HvP0R9z0CDfTy9FJq5/qBk7sBK2x/vQDQIhsF8dumYXlgyIywN70xcC9c0ME83ZblCv1DeOG32bdjhKxX2XKzYscgaG6+7Z8ax3x+prZ2h9V4ZBCWQemt45hyrmZo1vHuRDX8U6njzFvIWPotDfvPm5Dsn8s1clW+7REOkdBfGOo2cc58AYciIogy0ewkLSXYZ5amEq2OTrSBU9EGa/tvSVE4cB4ZqTyg5Z06f7mPRKYidHd4ZXOBTevcHrjhQHuK2NLYX8tL+rRrCPtqwjraqJsqg1yYOOTpBjBxpqyeKgAO42BCOaVfgIrHqNdyuFKOQ+IoxG+rrs1bpD4+9kWESOwQoHW0+zt6w4g+rBZh8aJ8LGoVsyQ2jDya1q/eaHjKdc9kQlB6NNPeXIoGsVC5/6HzqMQkOoBktsOf3bV71t1NmsLj7xvgzgdvGzcVoaXoVGJEu38UQCBhgmMh8163VA5BxNvHM7G4crRLhQp80372IhlZd3Txa105yYRJibncnfuoyEio9pC2ev
  template:
    metadata:
      name: s3-credentials
      namespace: rustfs
    type: Opaque