---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBZBGUGnxRgbHBxGZGrBGK/lkXqHFBQWpf+OYrU+gjaTAkyK5ZjcZBPHs8SodDmiWCA0Ycge1vsW57iJCe5FwnAvDcQ4hVOsYS9CaIGZxV7SL23wYMd7M37B1GaTscuUFtC/8qg4HEpera5EDIjNZ9q+ie8xmr/OIpTX1fra1JSs8gxFzOXqZlTplqLCf7ZA4mYUcCqZNcaCmYLk2iuXV+sw7M9U4DHYoW61+wafiNNv+7/FYJhtHP77A/y6v9AxiCWoX2Q7dsprEFoSslg53/0lakZ9De0GHDkHq2LcAg6rR2XndQBomYvfT9DrZDUl241OEvULAH5fYgP78p45j+ODbFSiH13mgfG73/HOfUxv+rulBzDN8UX2GTt1witNyRU7mQreiZE7DVgo9Hj8zAL+lSB+0+dtqPmlmLPUorjukhyKDIrldjARfrWXWw2ubTyIzkynePDLfDzMjSrlfkG9o73hqPQxHdkEb567u2eXL4xC8iwi6vB8o70DVMPdpdeMi0K1s4upGsCmytdpIeMHqpm5jbR3tbsO+viH/gXTd8GlxNRMEygaDNUV8NAO9qo1Ax1VmECvR+8pmoCPOQQCGqIYHgT97f2Hr1GZBOqxjuGXOARQJzLG14LMuGgWzS5kjUCUw1iD8QuRigszdxweZy986WWbzdE9vm7KnU0N4zj6Hq8EP0OJiw0D7k+pyZig6aK8g==
    RUSTFS_SECRET_KEY: AgBWXdluJX/efb02ae9DtjK+HLCdZgn4Iz7+gKU0Lt+oV53HcVoiaiIlGL8r7jbQ2LmqP18cA0cOyEOPvI/WgUOEIqb9SYVuMwNh7ZkRFzUlXp8kQ6kO8DUd3Ava3HowpivscLnP2Z+uJz5hpd2md72gI/rgdxV3MnOJZnDOtYblJ5zRmxMBKI799jG9qWleZpiwU89+VijB0D5fSYUf3NZpwCsTMX0YYtA5SC/Pfkd/bQiTK4ozmSjvJupu9LAprTOlOgiOijWanN3lrbuKLtDrGhFPKx1vnfJRwOjWRDV9w+L69dcMjn43u5c3f6VJgFZ0AZ7d+i9SWuslDKPCjzJhcalKknK6KWdaO8sj9A/V7IgiXvQx/aFwlaZacK6Pyx531CEsxQcaUFuiUNlldslX8iBseNO00TGsgc/d4MMq44OK1qNYVMa7u10+ZlEqbdumZulNxSrEBR72v8M4HEB/6WEO8oIvJvVDKl1wN6auMYktegeQrCD6Lk8qEEL7waFF2YN9mMoiPpTOYxnQmztI6RZsA8A1KbxDprPRid1gWjFSSy/wK8QHlrFWVEf79whSsgXOJFWNyIjze+mQ0Ccwd1IfjLLeHEPwd1ho0UWwBfbXtGP8g7efi8NcDWdNxDjzB+ARfx/OYk9bFG0qaH+RhL0I+8mCJhmOEiVYF9muonBQ3O0PSOdHJQN3im6tBvDJ4fM5l0S8v4l/roWP6dSD
  template:
    metadata:
      name: s3-credentials
      namespace: rustfs
    type: Opaque