name: oauth2-proxy
apiVersion: v2
version: 1.0.0
dependencies:
  - name: oauth2-proxy
    version: "10.7.0"
    repository: https://oauth2-proxy.github.io/manifests
  - name: valkey
    version: 0.10.0
    repository: https://valkey.io/valkey-helm/