---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db
  namespace: finance-tracker
spec:
  encryptedData:
    url: AgAwdOhMkWM7hiFdsPJfcjitAXg6o+GJCn0oi1H8RaevpLOeCVa0zj7F/iJeQ8Rfc36B9kdyZ/7/TKc5MLyABhJpfr4tYf8fKZJTtNPeUmcFj2fKu8Ne259ItwbXj2l7sQ5XdRpn8PkTluZSwFbK636cF/rqLGXQD/zbfyz9hVoKqcNRUxfQGxiyamDe8EKkDmgFKBOFanwKot3hWE+pcjhyqIO9brpIM0ikygyvb3WO2FD/pZXRWVpmsPWBvwfXsJWElS6bPz/IBFmjLMp6z12JC5ouCKbnt4rP8M8eDLmlHv6DLsH+lKDBnyiKOmDv6eRl7txs5el/nN1Lp2D7ka3xaOoKXkTJMjCa+dKzwsz+0pNZYd2/gjsqksaDTJ2hcSDl+m2GHLECI8PQEACjDtfaTCGZWIcje4sidEmYuZzVKLlSsBy9/ZyX3Dz0G9S0rbjWq43cpMoU4lVufbC1THxK7URMyUT3vLrh7Y3HxBOQdl7Uof7F6TWtQzzbAXK8YIDdfCFMsohi/V+i1tq+WuMpQFdquLAmhF5w3mcEEXvUKSS/Iq+Zz0XX9YkVw4JSQxU9EoWp6kszuiBo+Kr9d1lqhTjQprlqe6UlrG9k4Yb57Wo95TGed0+sBjsGfwIqRiJefhYxDyBSllgg7C0tXrmOae6ZY2Skt0bu3Qzfxvn2vm6BB08tPx/8CSC1eMZjC37P9dVRTpz9ZFW6ZOLPdKeRnLYdDHV2tfEUD+mK+oK1pc/pMlAnEqIsc9B9rrgmOvAmcjaz95jO/yfAKiMBq1pgzedOa2bxUElMaRilGYLJFxx55Wk9VxHyW+AZbyMAv2MLBoE86uEcR5G3AeW7BLQ=
  template:
    metadata:
      name: db
      namespace: finance-tracker
    type: Opaque
