---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: finance-tracker
spec:
  encryptedData:
    jwt-secret-key: AgAMTt21jy70DHw5Iy6UFZC73XWOjo8rGC1qhlHbCs+ha5KOQy/JVd2O9/KpuSWUHK0xbLYGHhMlCWTfHS2XQzdFg9MYjNAy2Te41CFho4QknQSXwCR+Z5IC/q+E4gjS1ZKizbhoBIgnjVUdYXQihPaSeLOJgjNoLNFC3Epukxtl3IZ0wp1JH8KudVjxp5rRX0WOyYwSCc9fOUQi4jUO++uWYF+Myt7A+CFP9jwmwAJEJjeHtrRcS6yh2I9nGU1sV4FT9OYQO9lFXL+1hKbo1f3kPam/t5zhW5nt2rZWB+pSWoG253G/PBV2nAEbqTerj+7wpKOa0FNdgP8BAr6aJKzB+z6k7RsnUu8hLIjlu1UVc3YAXt2mgPr+REwcHghi4oiYnUxNakubAVVh2C8T8sYb98ejch3FWb+wxXIsrOyaIl8HQLvXZXdAwHdJPT/0lOXi42crOm/rKPowBTvMs7Nm8VL0ou3ltrgT75jnNk78r8HHwEG2JHYyGaVvIGMJuxpDFQ/dI3vqk9wpTKA5QWlcTy2TSmC6r9NHttjSvp8Qkylrjx24ZShEfTcv4JILKJvvz7NlqK9mIo6sfM83TAdChmSXmWIQEWXdTaIczKXBect36elOC9nuMh0NM5VYpzeE2+SefKO9ZI/gkz1z0UM/CkT5jpaRDpK2aqDNOLqlnp3JP7IWaWCRYv79OGYKRyB3ZQrnLvCE0m+eL1zXzUr4nSvngupbYvpaMhnDL93hLM0X9hnCiBxvNOGb7A==
  template:
    metadata:
      name: jwt-secret
      namespace: finance-tracker
    type: Opaque