apiVersion: v2
name: dependency-track
version: 0.0.0
dependencies:
  - name: dependency-track
    version: 2.1.0
    repository: https://dependencytrack.github.io/helm-charts
  #- name: redis
  #  version: 17.3.7
  #  repository: https://charts.bitnami.com/bitnami