---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: guacamole
spec:
  encryptedData:
    password: AgBOg8FD52FMPU1qU+AwFoKYmwBHKGq8TK1nv85kWuju0uAtIJHQVQ2mIyAo5qbqUakt3DxSMzXh6KZeZnzNWEEK9sJFlqrvLt+/ejC/BSmTfQ7yy1xY+mP/sd5dvQQ3S5xjWkG1k+kx0/RSv7A93uUCloBQbvLwHDPum08dydgrqXnihiurtQWqs4xqnOtxmp89fgK/3iYDuKSdcloR7Am5SHr2WFid8nUmIjvWbIdKHid8x7ma5wGtSbkPEqIKkMCjkr4ouYy/lwkcK588j/D+hNWnwg4kgaL1LONfXe+K+Uy29pJ3C+jMp9A7X4vXJR59Q6AEVyYWyH9NJAVya/ncMekLiaOzH0vklttbstNk/ZPdohTdsFf5k/JSZcJFPTtkkYFEtyABKBJafOmK3dNr1R7qVD3iLZxyWii/y0wOt3Jq5Cpt2Z7x7zL62Fq/0b18R0KEYaDnA9mjilp9fu+S9l+abfCSIw7xXkLni/ic8dxbUp+3c1Nfk2dQC9RleVrHI+GMyO+hdJPJkbtd7gDXq6Pm4gcec1Hv6Ia4NjUN8r1Se4LGFszML2uz30IhBH/p7Qw5Zj6IfNp6tapfRw8E9ECIYT30vGZMppgm29vOO3BY7v8MX9BsiOQyGVBcvaTI8dFaiYl6FBwhXs0KPtC/ZPVomoiYxkCEX2cNYQtLTViZbxFNk2dbJB581Sze33HCCA+OdCiX65yGoge0AjnPQX+htA==
  template:
    metadata:
      name: db-secret
      namespace: guacamole
    type: Opaque