---
- name: Deploy bridge config (Netplan)
  ansible.builtin.template:
    src: lan-bridge.netplan.j2
    dest: /etc/netplan/50-k3s-lan-bridge.yaml
    owner: root
    group: root
    mode: "0644"
  register: bridge_config

- name: Check whether bridge exists
  ansible.builtin.command: ip link show {{ k3s_lan_bridge.name }}
  register: bridge_status
  changed_when: false
  failed_when: false

- name: Apply bridge configuration (netplan)
  ansible.builtin.command: netplan apply
  when: bridge_config.changed or bridge_status.rc != 0
  changed_when: true
