---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: source-db-secret
  namespace: club20-dev
spec:
  encryptedData:
    password: AgBf5pOz1TwRLRJs34iWuq9r9Y9FdcmSjn0V88YMLNR0+gAKa47wbERwD24GhMb9DDnpWRPaYmpZlRF4tUA9Y1OBH8okK2L/F6BoX9S9idUMbVQwP5sxYvB1IXI62Yp/h+3cg52zrSBWC2/X1XYgOJr7RPSyhBnbu1VyB8VJMHJERgEOSNtX7cWO9UsYWU5Jn4+/1LHW5O9FnrEklZ6CsiVNdmOoRZvxay7x+Tec2wzADffvil7z9+cLBkam8cD0mfZ+FPRuj0fWhDRtM1FguqS+HamvnNeLh/p6SmQkTtPAG/cGdKpuL5mD5/VgylhCY0ckIPem+2se6moh8yOKB+tZ3hTG1RFMI7/7l+16oc+qMNv/FWSN4MWjktPyzPC0nPVMT91DCKzfBxqr5/BZy4SQh0cvbVVhd8G9rTZxGkkhv5iPymDMBiRlSsatbAEENmO24xHOBgPZEeJAKfAoWLlnxuodpr1b1d5Kk2S2HF6ZR+d64Uh2Ol6MlGA40zZLpg6lMLTooR3Gbf8h56l8tkFDBc2yrERPbQbXpWKo/myK7iuMhLmwO8CabHuaiCjJND+FHCk/nCqkJw6WeAreerULzUZ2kCD0Hz/qju55cMba3CHTyPWtmuAmMYpRNALR4/3v53iJX5iJl3wkJD37tFjD3ieL6ffXObqsvi6sYz6hkTefqHDqNvOxi4EUssiwOqKKRXCB6ygm3LtJwslTIvINMF5S6gYTYcvKvGWUVUagFmpH9w+MQ8FGka/2FnBXQX0vDaDZ6qi1Eq/vFM24vOUWLg==
  template:
    metadata:
      name: source-db-secret
      namespace: club20-dev
    type: Opaque

