---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: source-db-secret
  namespace: club20-dev
spec:
  encryptedData:
    password: AgB7EIXNsMX3oEDdRFvFR/2GvAgvfQiuKmgMinlmkg2nbO1y0Tyh0Bn/pR5TC7ScjbvV/0Z+vzinWUHp4RtYSyArwvqmH4ToIAK8kaK1SazM9JTao6M1PqDfGang7QzRfVrOcVAcoKRPoEMvLnwTd8a08RdEJIBgbIGKwHG0ppffpoa1Bzj0r4BgEWizO5BHYussM/2c5lWhhnWb82jrmIa7DhMI7xCUf46el3OQH7QgTam6B2OhmK4DIX+xi+pJDfoskC0PLeconR4VzmBQ7PKINQ0ozirEXtN58q4pyjL4Myxq2zCXoe/ufACVcBLWUHasfMacrkyiVGy+x3NkR/tkWQZWieMvCbPtwZTKncSCPs8PooNwnhSxp/95QqmlyKV2yLOefJGmW2a4RLfQ+BiDWwiAbpfXOjkJEiw+Kfpe7Ywy1nVnXxw0iCDZ1qEKBQ3fjaCJgdwG9ktestNR6CPCNhzw10d8X6TJHLAKw0bo/mOjTPIjtyUnVWBX48fhZKEb0buejOFYbfhwbC26MeoZakF5xV7uGJMWdFh/9l0vu9SD4S45ltXC4u4kNuTICH1Daay+zrQPT21XMQlsgQ8HdjtPHVzeXrGJMf7UaOK0aKf8l1+4KZ+kfz9hhUXdC14mmpBK0ei2zH64euP5JXEAi1IU7ImhnN4TdCdvTU56z5tY96sED0v6Lpncy55TgcITlTc7+koJ1weZIPzLhJtTbagPhz+gQMrTLRvBZGjl4yBkv+PJKxGZphTDDxhF/5whxsrSOmUxa/GvnFW4SJps+w==
  template:
    metadata:
      name: source-db-secret
      namespace: club20-dev
    type: Opaque

