---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: source-db-secret
  namespace: club20-dev
spec:
  encryptedData:
    password: AgAyau9fxLCbA0fnvS3TM/aYMmsPSikUEDuC5XTIRD4cdM4MSU06Sc6J/3QYMhfO9qV1xtguDt1i49Fm9Y6TiemCigQrfYMXKKTW/9dOtRvyB4YFZVreNSFAPaVCmamd5O2d45gnEFmdWanmxXdrHnyJKdpDf8oGc9X5wSeKVGnjQcKdQhX74T+lH9e3XsS61sP9hZE6FpgQxQlb4qrxUjbOTtjh2NQg0O0tCpCec1+2pJGt4XMwqG5L9htS9y1QNn6g88TLPwmoqEGhzR7IfL0DMlwihl3fV4tN0c9UcZ1gHo/DBUPlHMRawz+dg8zMMoxdFhHmmAioXS7ew3UJ+DzprdhYJ19SLMkcCS1kny7RDz3vnqB//dMG1nMwT5sr7nd9bTXPgZbMZGKg2D2WpCNwF4Stf0+wtBVMWxUIKrOhqgwjVHGcY5LcbAaEZbws5HMSebg1h+eyDZuC4RCkYpoOOPa8GGFmtgv7rTDp6GIfv205iGqSYbGmHr/2Axk/hUqyeXslf6bzrkXznBF7UNlM73bZ82RlWfdbkg2XYwj7J8V6w7hMIoLCUHavNuAp2kXFMc4e3A3/6hK41zKF6g5A7bytrOanJcqt3gvQAj8MrUTcegbdSLFcggSrucoalrUIYhZV/fX5qBKGSse8Q+EQVTx5KeGF2uRs8plgnuYRw1z/sh3kO9lV9HYoWop78AR1jNHdvnUuYyiEXezgLqup5Hh55w==
  template:
    metadata:
      name: source-db-secret
      namespace: club20-dev
    type: Opaque
