# Lab example: default login debian/debian — change before any non-lab use.
# Console: virtctl console debian13 -n kubevirt-examples
# SSH:     virtctl ssh debian@debian13 -n kubevirt-examples
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt.io/domain: nextcloud
    fw.kubevirt-manager.io/vm-name: nextcloud
    cloud-init.kubevirt-manager.io/username: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: nextcloud
        kubevirt-manager.io/managed: "true"
        kubevirt.io/domain: nextcloud
        fw.kubevirt-manager.io/vm-name: nextcloud
        cloud-init.kubevirt-manager.io/username: nextcloud
    spec:
      nodeSelector:
        kubernetes.io/hostname: mars
      # optional, empfohlen bei lokalem Storage:
      evictionStrategy: None
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
          model: host-passthrough
        machine:
          type: q35
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              macAddress: "52:54:00:12:14:00"
            - name: lan
              bridge: {}
              macAddress: "52:54:00:12:14:01"
        resources:
          requests:
            memory: 4Gi
            cpu: "2"
      networks:
        - name: default
          pod: {}
        - name: lan
          multus:
            networkName: lan-bridge
      volumes:
        - name: rootdisk
          dataVolume:
            name: nextcloud-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: nextcloud
              ssh_pwauth: true
              chpasswd:
                list: |
                  ronny:nextcloud
                expire: false
              users:
                - name: ronny
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
              package_update: true
              packages:
                - qemu-guest-agent
            networkData: |
              version: 2
              renderer: networkd
              ethernets:
                enp1s0:
                  match:
                    macaddress: "52:54:00:12:14:00"
                  dhcp4: true
                enp2s0:
                  match:
                    macaddress: "52:54:00:12:14:01"
                  dhcp4: true
                  dhcp6: true
                  accept-ra: true
