---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: velero
spec:
  encryptedData:
    rclone.conf: AgDOKCjsUAm2mbY/n8WHYEgWXKxJFNOTcyDmPogBbBtokyynjAIeFE/nR1XWjqViQ/3xK/X4fDCUFuQWBrvvsbfO93zK4MpI0H/hBTHj9aCh8Nm10kMRZDdk0qct8UL3QiA/8AS+2SYaZ/oD2ssiJD3dB9Zl5SyhgzrcMmrl37lzNurcHjKrQqmzJalzQHbXor3ONvD+Ma6eYsndECrRgl+6xOMwvGu0Sk/UXOBg9x2XAvVptCFVU7lRd9NrItzwKFZzGxv9icDQtzLOojLmL6u/ebWtl/1Uf/NDJv1+Qoje2LqAQipYl/BRHD1xw2VXg1T6Yz+YQd3c+LUZTds+Tf4urLVdDlzde5FZkwgfsDzwzEQcdMQCUnLShGNpxw96VwU79xf8J9UTMp6uM22xOuskAGosU4/9jt9Lw6Ug+piIaeXfGCd0Blgmbn4fHwBLsDh7E3smMwj/WwS8jHwbg2GLtZvYfKVWNRoEOx8uhOyLLfvB2Z4OrqopjWSJg8+t1/X8FfsMP7AV4G77biYTLo4Qx0y3nBgBTdJ+IECxWK6vd+oJfhusU6gEB6I7Ej7rNkW2o5997YgJ6tsn01uBdT5aRVnkQt1uFoGpdUwLcewEqxLGCfUrkCzsWZbWnnhao8mujJnQiXNkps6j1bMvyKfytIX+KxQSDq3r/EAQJN5+sEInFHLkmWGoN5Txs77VIi3pm9Cr/CbEt4hEjFEYNml8Mk7jTRKPmvrinxydY7Gw5gvnsesBnqoUNzCZ8+15MbdPiBnpRaC1BXsDfP6pTdVRmtHlQ6cxqEtZ3+S6kXYwVv/I/cdauDSh8lR9tK1oYeF+9ttMPAFcB2rCfPwNGHU46py8Q8ZYP0EldMzceEGizZeWa/djdTlIAIih70wUaK4u5ag3xQ7y93sEJdOQuoCnGp6d8roc8tbC4jmaQt3V2DCjyQaWa96rogWFkp9RUQNlkU1JPw==
  template:
    metadata:
      name: rclone-config
      namespace: velero
