---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: velero
spec:
  encryptedData:
    rclone.conf: AgBmCLQL5DlduMgbkXZUt+wsE5B8GwBZLNkWyakYMvnBIf9BI1bc16N0BYdTm94/BogjW74lCXuT8vrexB4xBae19zsk3p/wfREReYcT3emtNv40C+IgEPXE8FPWSj7qDNYAY6JPxde2P0REjJipn7GjHoUcCdBCw4zu7SmgyFm6MGN4lXPc54x/j2efuJqESiz5jMPk/NgwnQUzd4K3S6D8MWW95DIjNLkJUFLtCfa9ZYat81Oi9iCyWuax3p9shv3l5QalGIdhxcC9InH2GVLn/nChdpGNq7gCQY+2SMECkAqLAqXgGQvpB/rbj0RNPPD1QdaQFb6CrqsOFpPBH5a3fDrEIk6R6K9e6Y2a0FGKPO0eornLlirKbcgP3qlgRaDoNV4TfYWO2zrhXcNLrrI5baFUBk/sB1CnpePJcs/TL8L4xu69M5PiDmxWLz6386QGTjFg8q6bMmAoDEh7GWZuCqxchH1uSqeolGom+kmVoGj3KX6x2vRICgh0PivGBC2xEryFxfyjR6WGRZfUuKrr8MSBzVl1Yya3Cny+L/Ba7xMsMhfxejUZKsCF+Sjs9HHbR6lj4W0swlUIOC7W3hWQQ8XoDuZftC7r6YTSVnL70pQ5ZImGhxFvCtbkurxSnl4GYudW6sJZqqHZLKJcb4YEJj1jzyzVGdxfCXPzI7f98y2oVM40udzxNRKecvaGATv2p5Ovr8VpwWfapHMigfQfEZVibGBfSEJpZDUgQlB4PTVLKFZDzQb5kayQ+G9dHZuhO/iooRSZw2UBbQzvDvkN3NbCGmlRu34Kuy4obb4rlOnJpDeNNKR0YxsY7fFj2rt/6RGHzL2MNeVcwOVwi5i5stmyxwXBcyjxVjD/4mxVUqoRbpTLbzSjE9tHwPDdO+E84RQC3D51euPU4A8UABra6QKuWpdVBR16476tQ+gt8oU42GbSGWahm3rsP1bwXctECNZWu1UgFE1LmQ==
  template:
    metadata:
      name: rclone-config
      namespace: velero
