---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: velero
spec:
  encryptedData:
    rclone.conf: AgCpKvo5Uvz3IpcYfZk5/yBE43AJAbS/e1jRI9k4IFOlL66/1rT1P+n5tcMymesIIGIS5ZA4S/GSuRlYRDi3V9v59CqAPozZF4ANC0+LkPN///Cx3LaCy2+lhdIs9Rd6QgdaCxt8aPN7uuabnolBhZgpWOkjaxP2+CRaXt5ANavb+z9MhvgXjmS8cbW24oEXtTwOgsiyup3AdSZGWCa9aoWjVv2PH2Apla8C64UzO99KL6MFOt08ZMvshA3rkoOcsoAOQjJxbQmJOKgaIJXNcc5R/qIhZc8Hfo7Kvig4vHzS4FELpa5e3GqO2zDVjnVPg6XDgWCYxClQmcF7ALa/IsW2wpfz+/AR0XwcHE/pbt79FH9i6y1sa9lRnLjt/acmP5tLrGaaAqzKs17RaKHhyBXtZDUZcxFMoIj8pPvK/d/ld0GqlBNFUmshy5qdVvdtwCJTp1tzdwdfZ+F0Qp/JrbKA+mTT3Ubx/JgaldbdPq5Wv1rGNj1uXeilPIuyr09oVrkVqVcbAJr0dZBNdhUds2U0DrDrvRtkBo4kN5lu80gfhAnrGBge01wA5pwEE3vqRz68ellM7ZyH3A3mb+GDCZMP1Ih8L4HPq9ikVuh2lHGTC+VPbSDmWocUzx36VMlmY7Z6kJIKgjI1Vd7Bt7OdXoWHOZrr0MJFQrIhdRvSdLy1iMziMR82Ncr71z4wcwqpw/+Octxb3Y0d30Pm/0vWfbyGx20csU44NjmOoY1us5lsb9xaMkXy2I0AZ+9jFXqX10EF6Yl7BtUL07qpKqtuJN05ywIu+8yQdRekcoNg35llYXFmxXl89w5Ta3rQZ/dK9+myL+qcznfThkKDaFyp6Ito6D7EFAKRYLzw6S/MGvbq35LGMS3cxyo1eyZzAUVTL5JjZ8MUZTingHScQo+f1w3IE7FXJZECFd+jykjNLwwrcN6ggD6yVDe7a2bg+yXYjTURUw==
  template:
    metadata:
      name: rclone-config
      namespace: velero
