---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCeDBZv764fYm2EbsKpkEGHX4ooXtmtOpTomOiM3D2bGHlQDrBmsK1VpWAHYRRg1Jim7XvvZhdfi0zA09qBAhaOCMkhCeorJs8QUkTQeg8J9fnFBM9tx4ZTwxjT0HsQCkB5NFUM/h71IY4hTczd1F2xht5BbBxnul9cFVV1VFGo+82tLhWHsjaArZdUQvr0wdrIJ043w5j7q1TGDnqLSVTfwqpdBo0EKw0oNABahOzjdfOB1PcDFsxVWReJDbrVG7vFqOAQ+MMHaJOwAMA/y/pZRWmjSNJOR4iu9fA8zVVaQYst+U37rSx6k1OCndaqcU1tX5Bo42XAhVtJFeMA4TosnijOmEzOC8Q8iVWis6u3TKOY6TCGOgNk0oVGG4+L0O9k/ZLDGt/wYmS1i0nWxUAb6kOuF7+vrvq5GG8ncrr7bC0JjSvfpkwntrCF9xCge5R47rYyzdrNAWpShcOGa+zLVqQNNpi5QasZvvgucpt8du13+LXyUHGb2yMKfX3pzyI5GAs3lonQwBgvM2LWqeL5O7k07S7I7otIeBo3mePFwWr756MaHV+9xiLMDpvsMxaJugXsT8zDu9UdjiKn+nQrCsfHlCYgLzCgChKQAYEQKKA5PBFcfkB816O32ustuz3yPSaatIsdNsPyKQLMp46tnKkpZhhboqRe9er9GYwCg/Ci7z6xqZ9W5unX00p+78aiR2dyFgvsKDXZCjdRsJxVYSSoAKHREbc2jikf4gBx0ZdHDgDtOaBRno82xAr8IS+OzWOncx5qr336OtTKkh/B4ziqNoZ6PMGxyyHSpBv0RzJGXA==
  template:
    metadata:
      name: velero-credentials
      namespace: velero
