nfs-subdir-external-provisioner: 
  nfs:
    server: 192.168.0.37
    path: /
    mountOptions: 
    - nfsvers=4
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
  storageClass:
    name: cloud-1
    provisionerName: k8s-sigs.io/nfs-cloud-1
    archiveOnDelete: false