---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-prometheus
  serviceMonitorNamespace: monitoring
  certificateRotateStrategy: {}
  configuration:
    vmStateStorageClass: openebs-zfs
    developerConfiguration:
      featureGates:
        - VMPersistentState
        - HotplugVolumes
        - HostDisk
        - VMExport
        - Snapshot
        - ExpandDisks
        - ExperimentalIgnitionSupport
        - LiveMigration
    imagePullPolicy: IfNotPresent
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
