apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  labels:
    recurring-job-group.longhorn.io/backup-daily: enabled
    recurring-job-group.longhorn.io/snapshot-hourly: enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi