name: sealed-secrets
apiVersion: v2
version: 1.0.0
dependencies:
  - name: sealed-secrets
    version: "2.19.1"
    repository: https://bitnami.github.io/sealed-secrets
  - name: sealed-secrets-web
    version: "3.3.1"
    repository: https://charts.bakito.net