{
 "title": "Sealed Secrets Controller",
 "description": "Sealed Secrets Controller",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Controller Status",
   "type": "stat",
   "description": "Status of the Sealed-Secrets Controller on this Cluster",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container=\"controller\"}",
     "legendFormat": "__auto"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "Controller revision",
   "type": "stat",
   "description": "Revision of the Sealed-Secrets Controller running on this Cluster",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sealed_secrets_controller_build_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sealed Secrets Total",
   "type": "stat",
   "description": "Total of Sealed Secrets in this Cluster",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sealed_secrets_controller_condition_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced Sealed Secrets Total",
   "type": "stat",
   "description": "Total of Synced Sealed-Secrets on this Cluster",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sealed_secrets_controller_condition_info{condition=\"Synced\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsynced Sealed Secrets Total",
   "type": "stat",
   "description": "Total of Unsynced Sealed-Secrets on this Cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sealed_secrets_controller_condition_info{condition=\"Synced\"} != 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sealed Secrets by Synced condition",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"value\", (sealed_secrets_controller_condition_info{condition=\"Synced\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sealed Secrets by Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (sealed_secrets_controller_condition_info{condition=\"Synced\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Sealed Secrets Synced by Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (sealed_secrets_controller_condition_info{condition=\"Synced\"} == 1)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Sealed Secrets Not Synced by Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (sealed_secrets_controller_condition_info{condition=\"Synced\"} != 1)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Sealed Secrety by Condition and Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count_values(\"value\", (sealed_secrets_controller_condition_info{condition=\"Synced\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unseal Error Rate/s",
   "type": "graph",
   "description": "Rate of errors when unsealing a SealedSecret. \n\nReason for error included as label value, eg:\n- unseal = cryptography issue (key/namespace) or RBAC\n- unmanaged = destination Secret wasn't created by SealedSecrets\n- update = potentially RBAC\n- status = potentially RBAC\n- fetch = potentially RBAC\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sealed_secrets_controller_unseal_errors_total{}[1m])) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Unseal Request Rate/s",
   "type": "graph",
   "description": "Rate of requests to unseal a SealedSecret.\n\nThis can include non-obvious operations such as deleting a SealedSecret.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sealed_secrets_controller_unseal_requests_total{}[1m]))",
     "legendFormat": "rps"
    }
   ]
  }
 ]
}