---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkhub-tronlinkhub
  namespace: linkhub
spec:
  encryptedData:
    EDIT_MODE_PASSWORD: AgAYQAofNtkiY8ldbKC+D/+3ievXGiwmqP31mpmLMn19XeUz1FQjwSKdMn3w1i/fMyP6iVPklAS51ReWRatCXkyWaL1FtpZdlYJTxf2KRhFOj74PEru/HBtQiGq/Ptmy2C6lDQZ0QJ8aI930DSzHnnoLRFWradGlXoIG1AFzziU11BhuQRo0wsRKQU80Je30KshtkbloxpjLwTIAPpWOsdn2MPfWyIk7+YAtIOYSJ7IRc04Tx1PSV6WC6ezR8+mx5uMSq8CFdxfMz8JYv3h3DBSvnehsUxGHyo+bJJKHulJYWNDoZAYw8mOG+4fPyiLrgqhgvJ/CQb+8PALCqzSQHh72bNOOXG+/U4F9nLxLVyRT3q4+Hy2SwH2I7hcLMfO4dLegpBOkWy9UY0dH46h6w+tQjGlbR4ygmfKTWsUTwPKhzDonE0zbufODBeigCu3mofW0qv6/E375HLAK7UnTmAv0W/CDDSOP/XB7sa3aLmydQa/G6+YtJ3//5MUPXEmqvxwa1bsWmE9HBY17zfNDKtrBVy/qLWOoLerl2zzfKULInrOQCy5VCrSC7Io523stmFzKvpFlFdIJ66uUqbC1zeLtiWq2EONqa3SRoFyRYkmG2x2VhWu1YbzHAJqKgPaPR8m4wH7xey2kmlOzXBSaE9uRWzq8Fun9HK9MSXVy+n8Hxiy0fIi8b6mDXghq4PxefgDsxXsuxPw=
  template:
    metadata:
      name: linkhub-tronlinkhub
      namespace: linkhub
    type: Opaque