{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkhub.fullname" . }}
  labels:
    {{- include "linkhub.labels" . | nindent 4 }}
type: Opaque
data:
  EDIT_MODE_PASSWORD: {{ .Values.config.editModePassword | default "changeme" | b64enc | quote }}
  {{- if .Values.config.totpSecret }}
  TOTP_SECRET: {{ .Values.config.totpSecret | b64enc | quote }}
  {{- end }}
{{- end }}
