apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: conf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: work
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.work.size }}
