apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    metallb.io/loadBalancerIPs: "{{ .Values.metallb.ipv4 }},{{ .Values.metallb.ipv6 }}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
