{{- if .Values.adguard.admin.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.adguard.admin.sealedSecret.secretName }}
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  encryptedData:
    {{ .Values.adguard.admin.sealedSecret.key }}: {{ required "Set adguard.admin.sealedSecret.encryptedPasswordHash" .Values.adguard.admin.sealedSecret.encryptedPasswordHash | quote }}
  template:
    metadata:
      name: {{ .Values.adguard.admin.sealedSecret.secretName }}
      labels:
        app.kubernetes.io/name: adguard-home
    type: Opaque
{{- end }}
