{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ .Values.ingress.tlsSecretName }}
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host | quote }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.ingress.homepage.enabled }}
  annotations:
    gethomepage.dev/href: "https://{{ .Values.ingress.host }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: {{ .Values.ingress.homepage.description | quote }}
    gethomepage.dev/group: {{ .Values.ingress.homepage.group | quote }}
    gethomepage.dev/icon: {{ .Values.ingress.homepage.icon | quote }}
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=adguard-home"
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      {{- if .Values.ingress.oauth2.enabled }}
      middlewares:
        - name: {{ .Values.ingress.oauth2.middlewareName }}
          namespace: {{ .Values.ingress.oauth2.middlewareNamespace }}
      {{- end }}
      services:
        - name: adguard-web
          port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
