apiVersion: v1
kind: Service
metadata:
  name: unbound
  labels:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dns-udp
      port: {{ .Values.unbound.port }}
      targetPort: dns
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.unbound.port }}
      targetPort: dns-tcp
      protocol: TCP
