apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound
  labels:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  unbound.conf: |
    server:
      directory: "/opt/unbound/etc/unbound"
      chroot: ""
      username: ""
      do-daemonize: no
      use-syslog: no
      verbosity: {{ .Values.unbound.logging.verbosity }}
      log-queries: {{ .Values.unbound.logging.logQueries }}
      log-replies: {{ .Values.unbound.logging.logReplies }}
      log-servfail: {{ .Values.unbound.logging.logServfail }}
      interface: 0.0.0.0@{{ .Values.unbound.port }}
      port: {{ .Values.unbound.port }}
      do-ip4: yes
      do-ip6: yes
      do-tcp: yes
      do-udp: yes
      hide-identity: yes
      hide-version: yes
      harden-glue: yes
      harden-dnssec-stripped: yes
      use-caps-for-id: no
      cache-min-ttl: 3600
      cache-max-ttl: 86400
      prefetch: yes
      num-threads: 2
      so-rcvbuf: 1m
      private-address: 192.168.0.0/16
      private-address: 169.254.0.0/16
      private-address: 172.16.0.0/12
      private-address: 10.0.0.0/8
      access-control: 0.0.0.0/0 allow
      access-control: ::/0 allow

    {{- range .Values.unbound.fritzbox.forwardZones }}
    forward-zone:
      name: "{{ . }}."
      forward-addr: {{ $.Values.unbound.fritzbox.ip }}@53
    {{- end }}

    forward-zone:
      name: "."
      {{- range .Values.unbound.upstream }}
      forward-addr: {{ . }}
      {{- end }}
