---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgAkFmuIVCRZXiVw1kMJwcjqgmU/uffAGOQFKkYOGmfMA76c1bYRvw7PbfpgNKLdMFUB3w7AbEB7nc0ppPFPzVmufnfNN1W+DSI7+jUNBFQevsV9qOnrXUH1m7eB7oIGH4xXBhHx0D4npk3pfoyd3L/kjo5ORolPqxFLeJBFhAiYmfU9uetjIfbBMjZRqghuewNMB2RwFDMmY/CnHr31ybJ6pkp9hnaJWPbnshvKTnnBGaKwu6o9lAr8Rb0UdowDXkxGrYaq1k1ejhEz5ByVjEZHiURqii9FVt0Ex/fRgtWlf897qVjYuk1It9ydcsGFm7gfsNkUN45w23dYZK0TFB+Mp7+YcJ87+Mh9pEhKulHzqxdOrlVvDNMD8qFGkzOf5nhnAvKIMsGPlXalvki/Km+0rnfyCx7Ha4kUzIU0GbCEv6Bn5uFNJtyhHsK9eLyPwrzi5+3V/mmUOoIeBSVg7xjcydeRRJhLa7qZKQr2ndFBhYCYR+ff7no/JHe7pid5WhUuZJlnYBPX3VPgOANi75MdE8MvDR7ip/0CsWF7tiOBCx61eIFvlt5IBPHkt6rxbyCpZtJ/6RoOd9y0UEVXrnwaY949QP605bYkqFhOAN/bUFTLO3oZRdsZ/VIqjw6KezY15ARqUnWNXFmiKtC9U8monrM/ZgdfGwJHd3btalZpsVCvvSEd67wx6fE9l9v8Q2g6bDC5kxbsF4PvkqB0KwbIc3bre3zL
  template:
    metadata:
      name: db-secret
      namespace: keycloak
    type: Opaque