{{- if .Values.lldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ldap
      port: {{ .Values.lldap.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
    - name: http
      port: {{ .Values.lldap.service.httpPort }}
      targetPort: http
      protocol: TCP
{{- end }}
