{{- if and .Values.lldap.enabled .Values.lldap.secrets.create .Values.lldap.secrets.sealedSecret.enabled .Values.lldap.secrets.sealedSecret.encryptedJwtSecret .Values.lldap.secrets.sealedSecret.encryptedLdapUserPass }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.lldap.secrets.secretName }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.lldap.secrets.sealedSecret.encryptedJwtSecret }}
    LDAP_USER_PASS: {{ .Values.lldap.secrets.sealedSecret.encryptedLdapUserPass }}
  template:
    metadata:
      name: {{ .Values.lldap.secrets.secretName }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
{{- end }}
