{{- if and .Values.lldap.enabled .Values.lldap.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.lldap.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.lldap.persistence.size }}
{{- end }}
