{{- if and .Values.lldap.enabled .Values.lldap.secrets.create (not .Values.lldap.secrets.sealedSecret.enabled) }}
{{- if not (and .Values.lldap.secrets.jwtSecret .Values.lldap.secrets.ldapUserPass) }}
{{- fail "Set lldap.secrets.jwtSecret and lldap.secrets.ldapUserPass when lldap.secrets.sealedSecret.enabled is false" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lldap.secrets.secretName }}
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.lldap.secrets.jwtSecret | quote }}
  LDAP_USER_PASS: {{ .Values.lldap.secrets.ldapUserPass | quote }}
{{- end }}