---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: clash
spec:
  encryptedData:
    password: AgDC8/2NczYHgLatIbbjbUe7dZQE/rwQOBW4yTFB08XrJso3pO0sKApuWa00c6ybvRBfcTXr0tqC3ErpxOcAmsAB58r8t07u6h6frAAgo8B5KvuL4+n7PZt1nenLpUx+cjiAVNz5jFJXtLyQgvN5pdS6OaMuqPxr6piW+Vt+qLBrRRnnK9YKx6F9Kez1KE7tluGz3zC+VcvVPAbv6NuOUeQCQrYa0LTW0EbiRW5bGinrxBe1urOkiteUp1z4s3tbazGGQhEFhPAICLNWCqpYT6QScj7++/Gy0U/lEIl2qsZQiGO/5muA8opqVeXgMgyjjyconwbt7v2gWWlV4SSqsYBtA6K0vzZfIi+P8fN6LHqRpmZVtYuCJyrtETQa/Op2/ag4D97U6R9c81YZPnAm03OTxAsQP+nFfqkRPpv7gu+k/SyCQuRUJmpvtB3BTvPGvWIVj845gkFiL9bl4hD18u22WXD4bXZ9EqZaeE5V9jPmWYx/SR3T7KJx3SWzCiDp/kQVdcUPI5NYLNiujKwSxLF3LjCHFHof/EIXF8RvZByxhk2GN62qyNv3AB4SsOJ9vEypvUcyM+1bjLiOxSozpppqOReFdXvzs9T0M7DURoe9l+PPEPJ2aDb6WJV90Enjp4klsaY/sBcEvCWkVXCFiP7Zl8OCiD11ndPZrrYSCuZmTFqm4Xz2OhfWCZ1NrQ9967usc5CIeMGWUpDrdFGDPxMHe2DgvOUc
  template:
    metadata:
      name: db-secret
      namespace: clash
    type: Opaque
