apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros
  namespace: kubevirt-examples
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: cirros
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 512Mi
            cpu: "1"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: cirros-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              datasource_list: [ NoCloud, None ]
              password: cirros
              chpasswd: { expire: False }
              ssh_pwauth: True
