---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-settings
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/platform/velero/settings
  destination:
    name: in-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-rclone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/platform/velero/rclone
  destination:
    name: in-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/platform/velero/velero
  destination:
    name: in-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
