---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: paperless
spec:
  encryptedData:
    password: AgB4iyzkWYGxizfejMbvelRX8MysxPP5StKY9LPdFez+Ir72XIu2xJt9OiUMn61xkbCFjI0rPQ3XsF0PCrhV3RV0zWT42OGqHZEMc8MeWlv0pKB/vwr/rWywxwyRvdWwjtqz8YEHqJjF19BEdU4QYBtYeDHkGq352Y+iCyMGBZU28hudcyHniXAgp936pf0e53ea3nyrpVAhV4LiZrwYJjg2oZOKkdSJI6AJZ667ZIogrlpGeWkTAqndI1agpyMOH8r0z+GXkUNYYP0nOU85I+vlSTlzBXfxWs7yX/As9vdT/R24IOwHOiILtdvDKD6bpLQI2vWSuW9lHhn6e8kWHdHNuBVNiYE0qecJENt9AINsILcujvwPa94MkbYzh3r935eoEouP5T7ubSg8MQeky5kAcwqSXqPSwovTTE8Y8RTk+BU1eQhBxPrnShfZ7QpFAL7huFchHk2UKF/BIw3vB9oI9p97dggYgfZwe89bAStbbtQUEos+B1+0absLUxE7PkdKyd883dNXF03PVFwy53kFn3hgS1uKV0mjFPpzKZ28IDWhhs/Ew8chSAnTLmrOsFBgT5VPhVQYI+iOkGyFKFrLud+BPSKn8C9BFuY8HOvDUxQA/DqWifNuZ/uPk+iXJIbGnm+D5Z9LTwybft166g4deR8NhTcCtw+i7LGE9WFJDSZQEjCfB1x31JSRivGq38J5D4kf0FTCo/3pftF5C06VL6gS/ExI
  template:
    metadata:
      name: db-secret
      namespace: paperless
    type: Opaque
