---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: dtrack
spec:
  encryptedData:
    password: AgBnVwkCT3nFrwz2HyzuH1/6QJ0StcvWbX4jLl/9aLD+01plmL6UfoWPH+7EwPDCGe7z78lWd+YzBImK3zJVMzinwPb7pkBrVE/X6QKfWCMzdWDsFzCw5ApbcELTayahyMwI0bCZZSUR9FjueCWdYMKBnDhe77utO6CS68uCv4tvbhV5p4XD/Xo5y4pVwDNRDSQfMNjwAPNScyOXbAk8UbuYF0SnFc5eO0fGiSgAEnOSu3KDKcQamXRSltPYyiut28dw6uTuJkOrQCVyyyqX2JLMxeE/UQTHW58FsHaHWu8ta9ESwDl3cc0kJNm/n+RElEHv/rPSfFJ+ETgXpWTiY8f26vuCQXDXdUfYP0qasOswmzKqGcE1j7RPVjYyGZGf+1o6s1+PKiL+IIjZLc5OjF2286yFmPV1qK1qsfYtVu7GQa+vIB6Gb8uKfCFq/6LBrpY3U3Wt1Hrj7ZlZfhss/6jyr4vhowHcq4CRh5WqVA3atnBqf+MS5WdCIslggPWMNIAuYxVA01Qe+E7bE53RXVoKwTiO9W12MBq81nqNlaHy49b4vpMttL5K0uhWKzv4hvoay9z+m+jRwGh5rxTOTB8JII6jD5odPuoGTGubbdjiyaUyG6TIRtx0yyIjvSarV+FOmh+/uED27Tbv5oeMxUQsxv8v9nNGMEPEcgp9ayWl4Y5hdBIb5OpmkTDEgQLR5uoOom7HJ+9GGMqVWEOWloaTitDmaVoY
    username: AgBN4HGpEvCmdIxRLvgQaaQ3yKml2nmBe3jXIqQ0wrsWqKclZnAJOvQBgnpyR34Li6pmH40R7mBZ4yrUZua/n/XxHEUXX6Mmx2x+xVkUBsrlqbqidQ17113HtUthhCucOwWMljxWInnTmQuYKDYGVImWDK96m1IsvSmQXVrHpgfBLI29L7GNcOhCZCDZn4GhkSSh8GBj58BobOh9BpvGaJSU1hR8SebmtELV+3ITxACh0B8iljeXNuHN82m12d3dR9AghfoGhBgr4K5mbV2+EcDpG92sky1QRb57EmyaeR1tT6U2KB2wjGxToEOMHO8nU9FUa/VjHUkk6thJcySd3pYEVYQHPSCnFBve0Pvv21IGWsyEfeI75gjiZyX3XOKGdkKo8ALjxWBUftuABIgCoPwT7RE1ud8gwMt5RO4qeXXTagg0L2/SkfdYE6Ov/0msqV8DQnJ5bOFP70osw+aGkLxOaGw8PKowYWJRWMVk0aBZe1qEBTUw/XZDEpIeIqLdKZfmZCjr3JVuzAanONvKqi2geB3LPyf+27mKXbdyhRJn/Cas/ZiVXIJ7mDAoGU8PiaCMgQJVLCG3+BYlRtyJzff0q8F2ZOK1/DQRPkFFjbTk2ieM3sc8FXmGjrCJBnUQ7/2UTQPxnoPIyUXHXfFJFiUHOeXxRv0fWntqTAy41M5p/Wo2RbhS3QePCW5AEEmOh/wn04lBWeE=
  template:
    metadata:
      name: db-secret
      namespace: dtrack
    type: Opaque
