---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kek-secret
  namespace: dtrack
spec:
  encryptedData:
    kek: AgCrg9ZyfWCMIuNZKEY8ldWNLGcWknbql3LukfYjx3mGSBlpGeSKKXQQSO63XeTnho9ybg0oxTRI7EgYTmcSqq5ttG8A1E5SkbQXaZDeFYLxjlINLczSSYnPC08lLm4+FCdYntESqa7DEq5pQ7XABx9aKbJX8aWExWigxzaEo0FLpCvA9iG7hZKXFuW/8zGOMQz7FTRvLMhgpHhSmJmkeiddgYcdE9kbcpauHQcVlU0DOOcEFioOShcKTF2padyQktQ9zjwfU16QqveRRVJif6dfkWJ++eqjtwFuPUyKfztErKaSItJ/uaiceD3862XXTDDwYpwy3vra1mn8jT6XFZvnX+271BsiPmC9p9R6iavKyhzKjMeO+v6/cduQJWU4z1Ev9kQo3e4IXtTgF42QlAYG0PnWlyu0kXkZo/QmHP9kmi83Fpk7H8VVFNRSiWDet5FwT2697XtyLcUVGyzzG1L8jR1e95Z1a47NcohLBpZY6Kidf9W7xHoleebSDRxJXqGoFOur0OjVzCg85UwZ69sNd7Vl6aBCFRwvz9j830wfFq9sJhXSCEKDydQ9ua5t0xvjUiybZkw4scxvZUyn4bwR/1KCkZjV1jiEMeTmNo+Pcz/Dkunm2ubAxNxS/3bBnEwfTVDqZAe8ARXRwRjKAc/Ake9BdIa7xz2NmTU0j2/jfYAgBPhBEmkDXR2jL8mjdXF4/jzPpbYcby5mWc3rvX3vKtLLVM/ItZ79ScwW/NBSuUxNDEMUrPOdyHmdWQ==
  template:
    metadata:
      name: kek-secret
      namespace: dtrack
    type: Opaque
