# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: paperless-database
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: apps
#   source:
#     repoURL: https://github.com/rowa78/k8s-gitops.git
#     targetRevision: main
#     path: cluster/apps/paperless/database
#   destination:
#     name: in-cluster
#     namespace: paperless
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true 
---
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-valkey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/apps/paperless/valkey
  destination:
    name: in-cluster
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/apps/paperless/app
  destination:
    name: in-cluster
    namespace: paperless     
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: paperless-backup
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: apps
#   source:
#     repoURL: https://github.com/rowa78/k8s-gitops.git
#     targetRevision: main
#     path: cluster/apps/paperless/backup
#   destination:
#     name: in-cluster
#     namespace: paperless     
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: false
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nextcloud-backup
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: apps
#   source:
#     repoURL: https://github.com/rowa78/k8s-gitops.git
#     targetRevision: main
#     path: cluster/apps/nextcloud/backup
#   destination:
#     name: in-cluster
#     namespace: nextcloud     
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true