---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: forgejo
spec:
  encryptedData:
    password: AgB7lMsZsK1eo9wMijhF83IOklJwCxAlCozTf9WT4/x1YkyChE8TfbbTQR00NN81P2RcXawH1TQrjpn3ykHgSqloGY2U+4LrplfrGu26lmiCLM+Vjg7QBorrcxTWX60ue7yI5vSRJE77F2tE+aSyCHN6Qn+8ARr31bbBqWDR5tUslFuyrUwBxVKFWCRMSVUdqiQjXuJFXo6mTErDsM6/0NLNNVZ/vNm1ce64MrC+RTl3ELuatGCzXcONkeg5OZI0VMmcvegj+/sF0fL8nLDGuaF7H22Todtv2uSeqWBZt595B25REdQf5qQZr7fYg3sW8+ih2rYoiBf+7/noeziZTmycxSCL2BURNUurJCKQTZRR0MPOl3dA/ZgSBdvkHHr6KXVXYSIHtNnZQZlPfnsyyVVLAaDufetvjwbiZv4eiaXnP8VP4l4HVnwjJjkiieTNecPsw1eQPAnHCL01GHt3v9NANW8m87hNDUSsdgaqE084+DuqOt6aATlE6n7GfwM1wK4am62P8AmksSHuwLRCd7xc5pcDPQDml6Q/hgBdIjkBp8/7vsHMflxHSr9gavt6+eaE97+ifiLVENe/qT9+54pgaZhTvRZf0GRpVIe9N8yVfzR6r9IHi2XV7+OrJs3GxTavQBffV7G3ZKtAeqs6dP2FmPLEXpViZUS5E5PY0HOYWftwZnP9rX/Qiq5Lcde8cXLmmPD7OiWolDRU3E/p3nXAi/9Gag==
  template:
    metadata:
      name: db-secret
      namespace: forgejo
    type: Opaque
