---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-smtp
  namespace: forgejo
spec:
  encryptedData:
    password: AgAY1UpU44+BFZAAlrWYL/C5neT+91wJ+i4815d7WW88aL8awA4H6qq80u0/ZLp14uGvn/FVAAnvsWre/7HxVVtJftpUkWTQMevckw9iGaACSz/ND8wtR4gT6RN6cusypXqsuYLOkHqIqm7aKLdyMN3k5gDr4ankJI5Mg8qg9YrcG5fz9wNaAZQ2VTlHwanbCofwtMezCHVVo3dGPEoAq1P2sHNVtRZgk21tsYxDwIntyJq1lq6cqSyaUy3YAbE2glvU+qwGP9j4/q9Mt9URrGDUxKdZqD+gZ1imiCnEcXc1WAFP++xizO7P4ww4f/lZrg08L408/RKopp6X2gUu9e7lx6dJtK8gQvaVT+/E/gyMxUZzQYUD+vd9c5CeROJuLkPO6HlHSfb9OLytaFF/QHVva4CkW5Ohk5P9+Z7K2EFT8uQvk1BKff0QYaIzlflauArYs2OsrSTU7ceQEts+6R15Pv4f7JI5EV3hiYtcvGgZJOnNKZ1ev1azsZ/ICEu6/FCpsY4NHnedZFrEyVUfwze5GPVojU17X52+86pFfsuk4IpXG+C0BIIeEBk2co9HIVtZ4gFB1CLWPUIZIhjLA187wUfoCM6tqxymn5+Z58UQjx5z+iS1b1V3Sj6xrvxT6CT1wTNtVmC5DN8JhstFb6ec7b15ZMtaTgRZKhsKuBab5Z/3YqzWesM4YykKco8WJF3vNVPdtpTI6dn/CtVU0/YNN6j9o8FQ0opN2Ly4P/lymzBD/nhbKPNv
    username: AgBoHyDjH35UGVy6NbGJB7RSZdjbi/x3rL3VttBnlGjGEHBzFnKQysnGEfKXnrfr3N5O4t/uJjJ3APxNOsSBAl9UkT8fi9wDhvgMAeyCeUOBEpbBJUtX38V/XNlYupiUtopPpZJ0Pn2CV+m0T9wmXrJW8sAUjzX29ly9xPTmWhxS3/RMjd3kmMADuZfIECoGV6m5KA3C9sm9JIjdlbfumK4eaxRhpMHXDJ6Q/YJ8mtMF4aA/IpPYqgTVG02nsuNMCq2NkVijY1fghGdaTTW+7oVWFD7V6fiwDU8NuvT+qrF9hyJuRcXoqHJ0xQ4LKJj/XR9hdx1VBpx++GO7slo5EHbJoQRAUKI+xHNpBwD8ZHcayfrQD8HzoOO5JIcD4pKZRoAy2iqoMXpOB3PRFlT+/3Fo8FSgBluVNJvQD+Z+UvNzDgjUL9P4X0WIrmdVxje7w//NhkP8Gi3oNEw0/w2B72hKvHDV/COcKfPng3E81Ue2G2U0sXox6JiIDqkgpISn0SLUT/LW9J0MIWeYSMqDvKb41Y18a7KobzbeezxJrlc/rzZIS/by9dWT0pFvasE3h4UQh7pP2O6andkOHJYk3usNiL8I4D8w8m1Z1ywmqAme0yKdDCtL1ylYJLzR5kZxtjw6MVKDpQvs6vnx/DTS+mNjSaAT9+yuKgd5iEhPcTN3F4lC/tN+1x50LKrtEB5D1v/xXr8alAlPBTKR0WdO+RioayV5
  template:
    metadata:
      name: forgejo-smtp
      namespace: forgejo
    type: Opaque