---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: coder
spec:
  encryptedData:
    url: AgC9e+EOD+eWFufhPjV9gntBs0/LrxBpbf+1qbfe9fERFO8tj7dAb/YNX84rXxBAvhZIIxsfFquEYweCz8EZlqZYI5V0sH5ZBhJcoBFzcC6eV48QwiJmXw9vWmS7rtwF2Nta5oEGCvHbAFh2dVxp4qc8aKcFroy1WADDYccmfIQgw22R2ksF4wrFGwXBBsjy9x4jCTpB3rg6HMFysqbmvHVSe0IZUU8aEkogxhcXdMsprLKEMDj/1EcKJWWhjVSJDgtfTuKXTO/RXo4qjQxcJTvO6MqoNy3CNuw8EhzikZ6ViGrUGFVhKZ1QPjYkE2U2ErXnsgo3+fNkM4PcuMDCob64SEgJ6OdeYJrwNLM8ejRUxDLdth/0GuBra8jMfhq3ggTgLyH+Uiv6955ueggRVyprMhimiLxuPY7Pws1S042nZJV9ks77ZpBzohorR+2KkNnPamgOm9ybjxLFaofqAhCmHVj9qoieigaTnMhePZZtD6fNdEecVFmxMeva6HaY/HWxbyrOmwmkYwKgyIuFYlWT/CLBt0aEzc0ALJUJYHlt/ytJvmFSuUZR/aAUURddEwfqaaJjcVACnDTWEwu5vk5z3j+A5GOpY/Jy8jx155ngfHZnGWWDhIGOQ3oXEA8eRu7ztr7Xt8NLk9DYVNpJYgV1S+rn07QCP4bXZRg5Ns18AbzkeihOzRiJFuNUPweqtvt2K8FqY37n32aHwj36qvOq+nsCTqIHBS5NHNQDg90quVUMssLHA/m5zUdMaO6BeNudTbuqZaQHYKhNhnyuvWMieYaBiOsV4/Ny/pWWZ4HRK3+/cOy92+Y=
  template:
    metadata:
      name: db-secret
      namespace: coder
    type: Opaque
