---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db
  namespace: coder
spec:
  encryptedData:
    uri: AgClbrX61lLwcDbl/pFp24LeD7UhDR8mPWHr4FDyCxfm8Ge+ICwqBjnDGnQ6JOHJOrbf4/yHBqs7EAPvSqE+5Gu1oEIa6y8JKOjxHgHN4MW7jAsrnbZvP3OZKWNCvTq0nZs6RcCKkdKlo2ToB/V6S2c30ZGMMlgxzdnHAcKyaNyvttAE3S4MhNWb1PxBQfFMcfb5w601qF+4CNFmnEkFNWid04iwwGHTBk44NMhxDNlZwa1DQOPIVg/Cb8RAhShI62PUUtxvUq+CQzy/bvg0v/+nsQKkULSpUAQjK6dWNbdOde9l5XcBUuUcIaAjD6b/WmkfOaV1AAPna3cixGG4ApezxnaHqlwVn1nJRcatWAdalncsXzmCD/JqPEfxwHcHcT1LTfBgJhJ+TqaS1FxF7exlyR7+8snt3JZPbMryQIhEBGqEwbPMBqAEs/awQIa7ymcWF7d2Zr4rFKIsWBIspEiTasv2rmfT1WOGC0sDR+oRjLJ5/HLXTGX4p9eVHmn7wmgufRuE7W2jo+6kfv1MVyG4AHOOdW1j8bDuwYyrS3xGis7dIWFKJKP7zc/C6mjFu0qYemNkOktSxa1cnJ5WI9FVviGVUs+887TeMnniFCMnjnMRHaQgb7vsU6OpZJ6eqWPv00VTaJWTJ80KQdwB8teeY8pFPueI5FKXpp716eGx2Ef8/THbKrifzt6VJ4eGM1M2I1egkxMlNY6kVzzApiTCZ/xjpXS1fNvPtpRor5E7Tv9GoTrpCNJsks7rhSddu/7mjJQiLLgdUIN9RlZj9Y5HPe8S8/NsQt0m26L0duWBhXIv0kl+tOs=
  template:
    metadata:
      name: db
      namespace: coder
    type: Opaque
