apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: clash-postgres
  annotations:
    k8up.io/backupcommand: sh -c 'pg_dump --clean clashdb'
    k8up.io/file-extension: .sql
    k8up.io/backup: 'false'
    tailscale.com/expose: "true"
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog # Or 'ImageCatalog'
    name: postgresql-global
    major: 18
  instances: 2
  extensions:
  - name: vector

  resources:
    requests:
      memory: "500Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "4"
  bootstrap:
    initdb:
      database: clashdb
      owner: clash 
  # bootstrap:
  #   recovery:
  #     source: clashdb

  postgresql:
    parameters:        
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      hypopg.use_real_oids: 'true'
     
  replicationSlots:
    highAvailability:
      enabled: true

  monitoring:
    enablePodMonitor: true

  enableSuperuserAccess: true

  storage:
    size: 10Gi
    storageClass: longhorn-strict-local
  walStorage:
    size: 10Gi
    storageClass: longhorn-strict-local

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: minio
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: clashdb-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: clash-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: clashdb
spec:
  name: clashdb
  owner: clash
  cluster:
    name: clashdb
  extensions:
  - name: vector