# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: clash-postgres
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: apps
#   source:
#     repoURL: https://github.com/rowa78/k8s-gitops.git
#     targetRevision: main
#     path: cluster/apps/clash/postgres
#   destination:
#     name: in-cluster
#     namespace: clash     
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true 
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: clash-backup
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: apps
#   source:
#     repoURL: https://github.com/rowa78/k8s-gitops.git
#     targetRevision: main
#     path: cluster/apps/clash/backup
#   destination:
#     name: in-cluster
#     namespace: clash
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clash-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/rowa78/k8s-gitops.git
    targetRevision: main
    path: cluster/apps/clash/immich
  destination:
    name: in-cluster
    namespace: clash
  syncPolicy:
    automated:
      prune: false
      selfHeal: true