---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-api-keys
  namespace: xopenwebui
spec:
  encryptedData:
    api-keys: AgBWLs/0MYPCZfPSRIdtjvubswrjOU1EvaOLkqf5PCVZXfiasjQHDpkZBSbj9Q/G3oImZwI27mIZzY5Z7U8aPBMQFlE8WKxUtXrtzCGzxqfccDGNo9i03QJkIpMNAKuPGA6ueTkH7AQ8oWr/BgJGpOZzEfVbSBor35XSPpZaIODgXBeZBk1N3osbY8pPH2P4kxmFq/IDo3+dFtiI4ZRHwNSq1T1BoWHxiR/VWNYvwBhHoIQGhbgtETS+S/Ji5kR8+dLYoNKXUnkYuqeBq0NVV1ER1kYzH/5l2cJMYKzEp0zzklTSrfK/akcLKX6Ne9F6E8ETL+DNlAC3XFTkAvfPhuvGPV+1TdteeJ3qvScMG9MhRWO/T5/ZQRjWX0QMefvnjVMFiwfNhqIKBXGNmUsNN6bEXHPY/8yFBP1DEiGF1+yPyymzyKB7LALbhkXhieTFy8DJUKVo5VBvDVscJ+h5d+C56KLK2FXBQa/3b5bpkYrZI7kg3kVGKt7Yy/2vYSeUiXh5sjVCZE+6EjBZtEHuELbKWRFKLo94GwOynMtlzwX/SaAXfZOp/RWCv+CvfY9Ym61Cpr4AC4hhLlcfPGCZN75IN4PSCOTQ24abTHVv61bGqC3/wY8RiI/7SRGq71+OrelogXVuo+0MWYkv2VF+TQlWK00MeB11JqEx/BR516V5mHy8kO6oZ0XXIvTZ2RFiKkF3WrqboTjiWFsGV9+9CWc2+FvkwuAfNdfnC/V1sQXFG15nADhWRFuPxbWrRqGRWTpj7EZbPyCQW1s1JHiTzSwhtNsAtUJC32KP
  template:
    metadata:
      name: openai-api-keys
      namespace: xopenwebui
    type: Opaque
