---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firecrawl-secret
  namespace: vocabolario-dev
spec:
  encryptedData:
    api-key: AgCYTGxm5fED0Hcez8Rp6WCkDQcNZSZXuiU4DC9uTBjtgj7Z7+Kb90mO4TH/2vjSdCT0WTYkLcl9nQMkbPO39P5de45NFIjkNTQjpbqDKYI6Me59wBywdi9YuZ20hBNnp0AbXiZ8Zampbn3vWfOj+VLDNnGe6eYFYd5gWRm7pgyXBEtrKFtf7vubSNJDY/fTglw78SrqbZSGpdtLKomelV8i9/4+5XYGcrNReK4A/5u+IBuRgbEf5UceTISyommcKyazEzrYLNpyssm6K9s+qNKtfWfVTZBzGifMSj4UwG0YGBA3D0EBoGc8ENr59UguxGKJAgQ8ATF+p2DfxZIq7zTg9iGHJT0xq28ZEppyn5WrcMcyCDkCfw9zYow1xoaLfGq44kxDgTnlw1sRUgMQmhUjljxLbzMQ15KI8TrEVCGLVLLq+X9qkORQ2pzs/hGEPUNXtDFtEkUzgXPq3f1neyaamDWekuZleqyZd8ch9HE1tl7fa45hlJwB2qZpS1r8d7cAAtDH0oqLDTi2gIzGIYArvuQtooT6RvD3MEr3Ll2K50VOTdJPK0l/dXRAKNMJRhIJzqXFJFmlCaz/L5gQcv07z7c/lD3igmIQKTpdj0+cqxf4cKIrvhwvkCqfZD3mK/ObwToj8Trj2L+w3YQpf/9yySI+srCh2w+GWhD1pxCuVNzpKh4G6R32j/GHdYvLFTrluGx9f+rLTEQSh5NI9XEwriyU4lhyMEEuOl5hZyAXYr9bXQ==
  template:
    metadata:
      name: firecrawl-secret
      namespace: vocabolario-dev
    type: Opaque
