---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: vocabolario-dev
spec:
  encryptedData:
    jwt-secret-key: AgDLvfvUKSx6tMERR9TdUTC9bxSQufRUZQSR6ONqf9oVzmXfz9aVrCNav2cuvcGuc7h2XHQEKibNjt9tEpWBaAYrj3XoMHYk1ZyyonhPWf0QxHp0sp9BN0KGIrbXlsdoIXlnfiOyBySrEkBj0nHnE62aS2JMSipWu6MrIOFuBBSH7ODarsNAq9cnyrp7kiV4TDaLBJfE2QSLFyNq+qwg8OkMXgLuXR+itfsFWbxLvTuKebZIgsnftfqRh1lNX3eG/g8hzhIeEsNY30musn6L1nLIoLy8Y7sPb74BZHr+V7J8v8X1ca23mM4IP5yM/6LL/CalX9crViKlys2LQqtN9tllgwz6mK7VHTCbX0giZVbgStLP8tEm+OMKxx5kQcpPKhY85vY0JuSMb/CD412UQGLxzu08oOkOZbs9xtvKiZE8h5N8LGzBH0Q6oE5bkw1C9djWxkd/TRFgfMsYO6QtcJM+Gjwh7cXxnuAUKU5OWKI8XYu1hlfHy0ZFu8wi3uB08IiAEzAtkYJw1PyqhzVyRYBulRTE+M+SxarrXaZo0e5fwqS8jjm04x8UbSsW5JNaFyyRngMIg3BJMVuhuqXd1GmFgwzuxddXKTOofLkGwBIZHhEZ6xJFh6hNU5BoYKYQz5fkUICranMlFUAWoqXvnTK9ihA7r7sZ6E9IkIjv+G88q5NmwJEGVBrHlno51YviSQK3gOwR8j1k5HMq6iU9u11RzJPMNWXHGyde67Bmyfc1HYiWqCPk+xU7VDd0zA==
  template:
    metadata:
      name: jwt-secret
      namespace: vocabolario-dev
    type: Opaque
