---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: source-db-secret
  namespace: vocabolario-dev
spec:
  encryptedData:
    password: AgCPftWYYihwxkkTxYsUFucjcsieVNMrq0Mp84cA5YqJr2i/oCBP3T1aZ4Klgvt4BnLjRc77vwn8rbB9bwyJj6nZVyAbW9tOyv4s0S4h5d4WnYNNQtD9fgRmuhZ5+xSuNJOw9nIXpDramuwfba47rQVPN/MCF5RgLX3OOiQzDabV57uR3Te0VIlz6FsB8FhvFZJ/8lKn+cvLRghs6YqR80RmnHx5EWbHrPnlvlchYaL+GQGl1FoMvcLat2Hirb/8guEqTuz5TXPmsIJl4SXvd+DxQp9u72UXPlrGrm+CKK/0f9tEtPOK76TBWIF7ZusIr5vCHxiDmGVqIj1wQT9LaEwr2ArlIWNKqdfGzx7O3KkqWcjWn77m3m3OZR+aZgn9K7Nt3lxmqtB7kXMvdaM9XD1xMQRB7JD6IW7FkHe/bKe+ZBXDPnRhPwBN3vCTLbXUw0KMSny1UNryd4KPucZzMeuvBxrWJ0E9IOrMpgG6cjMdTYgf9ryM2EIF2ozgsCcaj9Tslp750ObP+2TFTUXVV6SRAIOx22ocDuWGDLoxEk65vI+jrba9JcWzNUIUgM5JZJQG5WKmWrs8oX0z8vs+VQnOWTJ9z8czOSZ7qDcDTzuFiyYtfouLErbP+GwLS+Q8aRx+bzBLw5MHnyXp/eFtIVYm6p+FQ7QHlxF5cPRdnxbIU9iA45HYvcXNbIQkCQ7+1M6N2yYsQxWnoAtxFQHSRZkb/t5LoA==
  template:
    metadata:
      name: source-db-secret
      namespace: vocabolario-dev
    type: Opaque
