all:
  children:         
    masters:
      hosts: 
        k3s01:      
    workers:
      hosts:
        # cloud-2:
        # worker01:
        # worker02:
        # worker03:
        # worker04:        
    k3s_cluster:
      children:
        masters:
        workers:    