---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate
  namespace: renovate-rwcloud
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBUGLGTSZJExScg7HoGX/JL6gMhMH1B8sAMseew2kRRuCnkzvZyecm4EiBkL534oPoIpp4GmM3PiNnvTkCah9mIEbvbYusCl/i7LXsvctAXaJZCyWFt0Su6L7JPor/dDk+U3O1bI8h76il/OojGonRDaXurOAituCv3t/tBmXiZbnWQXkYEjzdGON4OVIvvIk2D6+1LWrtzhiXipYxM6/uE65RQV/av3F8FfvAnkAQSnrq58+ynJhYT8mpf8Ti7OJvdgnQSIU41xppsRk8uq6f1U2Sxt3bcvDZ8Jdvx48nnpWi7NJULCgrXyRyjTlHze/fHqj0m2janCrFaAFJ9dSFGF1++XqfNPuLbVUkiZstofmfjJVDZkZ+6FGmM1Rc0IJeCDjaThQdFplDMoUOuXE3w5SKwHoBe9LN4O35gkSFup+9/WuVQeOPfcYSyjVpDRs4tbOcst2FgE/pNz7SmwFSL4wG0hn5iJcsQO8SnKyczbFCju5W6cH0b/Yl0vIKfhWGIw2+7fxk2ET69UtJ1g26siSWYCqJQW8lCJLetLPPyZdDJlgnCL4/NFxiYDMlcVtAxuGGpEIB4VssIVjDftmeGhHiJcpXXVCxzjO4L7msCWcLDQ/Lfb8h8GtoQLKVren2MArd7cntHi4y2/iKs/jCzE+3uoOaVpRX2X8HKgJprKOmIQKJaIvARDKnSwsE0s151nVz3onrAKihPGfvZHZYQsSHzdanpcl9pm3HjQmug1vFJqhXawNd2
    RENOVATE_TOKEN: AgCImJ+89Var55yI87DB7EfuUZj1rW1BkOxlm/cPz9QScigvQgGpIOgDFQ6tr/NEXxIal2P6C9rbqud+TLADw1UY/0iZGwEDMRBejFS0fLgZoJaLQ5Idtxzvv9l/xsrygJvLoXdcdpniyIPGUyBgwtkcUO92tQXT9ktQDe9N0TNRJZZZyeIjatoLLa3KvrVQfTjFYPCG1/ZGCZQX1wYIaasrgmb6VG2tcy4w/NEsPHUUa+hYmBx+BuVx8FspJW4Z0o1uUrAZaUEcLaMpcJLLBabgIE3IbYzGyVQjX4I8LfG2UOVHaQV4fCiI5TePCYB/33Thmri+alOqT7yMmiIlQI7MRh79ktrJ84qWLmewPMa9Gf3FYq+CoWs5phklBwrq4s/LOZXH9y3m/Zo6NT59UrPV5tHrcaTXWd3YC5yY7oEHc5JSvC30oncfx7pmjWWvHwHkiTROK2X34Xxe8l2mz6jiSdJHobDV7HUYj2mYvuqM0DbA/Gixnlw6kNjZKXpPiQqv7RrNqg42TllEbmJ8XwUSGiSSEivazkxyPR6MZbJSjPl/7nyMZXtaaufii70SHBkFWJ9LbkF+xRVdPg6u80Osjtu9PWX2Ek3Le8UVJ1EaSeCg/JUy7KeskB2MC/s0owPgIvLmP02YSI3shVsbxQuyQx/YU23at3671a6b+zUxi6ODmhQ76AEc6ql5AkW4OVp7GjSFJt8GwuDDWaaki7dhmfnU1gBlm8xH5BJap2C35+SpWtZ+qPH7
  template:
    metadata:
      name: renovate
      namespace: renovate-rwcloud
    type: Opaque
