apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubevirt-manager-tls
  namespace: kubevirt-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: kubevirt-manager-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - kubevirt.rwcloud.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    gethomepage.dev/href: "https://kubevirt.rwcloud.org"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: KubeVirt Manager
    gethomepage.dev/group: Platform
    gethomepage.dev/icon: kubernetes.png
    gethomepage.dev/pod-selector: app=kubevirt-manager
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kubevirt.rwcloud.org`)
      middlewares:
        - name: oauth2-auth
          namespace: oauth2-proxy
      services:
        - name: kubevirt-manager
          port: 8080
  tls:
    secretName: kubevirt-manager-tls
