# Blank system disk for Windows 11 installation.
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: norgate-vm-disk
  namespace: norgate-vm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    volume.kubernetes.io/selected-node: mars
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 80Gi
    storageClassName: openebs-zfs
