apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-data
  namespace: velero
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
