apiVersion: v1
kind: Service
metadata:
  name: rclone
  namespace: velero
  labels:
    app: rclone
spec:
  type: ClusterIP
  selector:
    app: rclone
  ports:
    - name: s3
      port: 8080
      targetPort: s3
      protocol: TCP
