apiVersion: v2
name: paperless
version: 0.0.0
dependencies:
  - name: paperless-ngx
    version: 0.24.1
    repository: https://charts.gabe565.com
  #- name: redis
  #  version: 17.3.7
  #  repository: https://charts.bitnami.com/bitnami