# k3s uses a non-standard kubelet root directory
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: kubevirt
spec:
  template:
    spec:
      containers:
        - name: virt-operator
          env:
            - name: KUBELET_ROOT_DIR
              value: /var/lib/rancher/k3s/agent/kubelet
