apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  addresses:
    - 192.168.0.240-192.168.0.250
    - fd00:2222::240-fd00:2222::250
  autoAssign: true
